export const environment = {
    production: true,
    restaurantSearchUrl: 'https://learned-iridium-391519.ue.r.appspot.com/restaurants/search',
    loginAuthUrl: 'https://learned-iridium-391519.ue.r.appspot.com/loginauth',
    logoutUrl: 'https://learned-iridium-391519.ue.r.appspot.com/logout',
    registerAuthUrl: 'https://learned-iridium-391519.ue.r.appspot.com/registerauth',
    passwordAuthUrl: 'https://learned-iridium-391519.ue.r.appspot.com/passwordauth',
    passwordChangeUrl: 'https://learned-iridium-391519.ue.r.appspot.com/passwordchange',
    userRatingsUrl: 'https://learned-iridium-391519.ue.r.appspot.com/get-user-ratings',
    storeRatingUrl: 'https://learned-iridium-391519.ue.r.appspot.com/store-rating-auth',
    restaurantInfoUrl: 'https://learned-iridium-391519.ue.r.appspot.com/get-restaurant-info',
    addDishUrl: 'https://learned-iridium-391519.ue.r.appspot.com/add-dish',
    removeDishUrl: 'https://learned-iridium-391519.ue.r.appspot.com/remove-dish',
    dishRatingsUrl: 'https://learned-iridium-391519.ue.r.appspot.com/dish-ratings',
    deleteAccountUrl: 'https://learned-iridium-391519.ue.r.appspot.com/delete-account',
};