export const environment = {
    restaurantSearchUrl: 'http://localhost:8080/restaurants/search',
    loginAuthUrl: 'http://localhost:8080/loginauth',
    logoutUrl: 'http://localhost:8080/logout',
    registerAuthUrl: 'http://localhost:8080/registerauth',
    passwordAuthUrl: 'http://localhost:8080/passwordauth',
    passwordChangeUrl: 'http://localhost:8080/passwordchange',
    userRatingsUrl: 'http://localhost:8080/get-user-ratings',
    storeRatingUrl: 'http://localhost:8080/store-rating-auth',
    restaurantInfoUrl: 'http://localhost:8080/get-restaurant-info',
    addDishUrl: 'http://localhost:8080/add-dish',
    removeDishUrl: 'http://localhost:8080/remove-dish',
    dishRatingsUrl: 'http://localhost:8080/dish-ratings',
    deleteAccountUrl: 'http://localhost:8080/delete-account',

    restaurantSearchProdUrl: 'https://learned-iridium-391519.ue.r.appspot.com/restaurants/search',
    loginAuthProdUrl: 'https://learned-iridium-391519.ue.r.appspot.com/loginauth',
    logoutProdUrl: 'https://learned-iridium-391519.ue.r.appspot.com/logout',
    registerAuthProdUrl: 'https://learned-iridium-391519.ue.r.appspot.com/registerauth',
    passwordAuthProdUrl: 'https://learned-iridium-391519.ue.r.appspot.com/passwordauth',
    passwordChangeProdUrl: 'https://learned-iridium-391519.ue.r.appspot.com/passwordchange',
    userRatingsProdUrl: 'https://learned-iridium-391519.ue.r.appspot.com/get-user-ratings',
    storeRatingProdUrl: 'https://learned-iridium-391519.ue.r.appspot.com/store-rating-auth',
    restaurantInfoProdUrl: 'https://learned-iridium-391519.ue.r.appspot.com/get-restaurant-info',
    addDishProdUrl: 'https://learned-iridium-391519.ue.r.appspot.com/add-dish',
    removeDishProdUrl: 'https://learned-iridium-391519.ue.r.appspot.com/remove-dish',
    dishRatingsProdUrl: 'https://learned-iridium-391519.ue.r.appspot.com/dish-ratings',
    deleteAccountProdUrl: 'https://learned-iridium-391519.ue.r.appspot.com/delete-account',
};
